table Date
	dataCategory: Time

	measure _ShowValueForDates =
			
			VAR __LastDateWithData =
			    CALCULATE (
			        MAXX ( { MAX ( 'Spotify_Dataset'[Date] ) }, ''[Value] ),
			        REMOVEFILTERS ()
			    )
			VAR __FirstDateVisible =
			    MIN ( 'Date'[Date] )
			VAR __Result =
			    __FirstDateVisible <= __LastDateWithData
			RETURN
			    __Result
		isHidden
		displayFolder: Hidden Time Intelligence

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	column Date
		dataType: dateTime
		isKey
		formatString: m/d/yyyy
		dataCategory: PaddedDateTableDates
		summarizeBy: none
		isNameInferred
		isDataTypeInferred
		sourceColumn: DateAutoTemplate[Date]

		annotation SQLBI_AttributeTypes = Date

	column Year
		dataType: int64
		dataCategory: Years
		summarizeBy: none
		isNameInferred
		isDataTypeInferred
		sourceColumn: DateAutoTemplate[Year]

	column 'Year Quarter Number'
		dataType: int64
		isHidden
		dataCategory: Quarters
		summarizeBy: none
		isNameInferred
		isDataTypeInferred
		sourceColumn: DateAutoTemplate[Year Quarter Number]

	column 'Year Quarter'
		dataType: string
		dataCategory: Quarters
		summarizeBy: none
		isNameInferred
		isDataTypeInferred
		sourceColumn: DateAutoTemplate[Year Quarter]
		sortByColumn: 'Year Quarter Number'

	column Quarter
		dataType: string
		dataCategory: QuarterOfYear
		summarizeBy: none
		isNameInferred
		isDataTypeInferred
		sourceColumn: DateAutoTemplate[Quarter]

	column 'Year Month'
		dataType: string
		dataCategory: Months
		summarizeBy: none
		isNameInferred
		isDataTypeInferred
		sourceColumn: DateAutoTemplate[Year Month]
		sortByColumn: 'Year Month Number'

	column 'Year Month Number'
		dataType: int64
		isHidden
		dataCategory: Months
		summarizeBy: none
		isNameInferred
		isDataTypeInferred
		sourceColumn: DateAutoTemplate[Year Month Number]

	column Month
		dataType: string
		dataCategory: MonthOfYear
		summarizeBy: none
		isNameInferred
		isDataTypeInferred
		sourceColumn: DateAutoTemplate[Month]
		sortByColumn: 'Month Number'

	column 'Month Number'
		dataType: int64
		isHidden
		dataCategory: MonthOfYear
		summarizeBy: none
		isNameInferred
		isDataTypeInferred
		sourceColumn: DateAutoTemplate[Month Number]

	column 'Day of Week Number'
		dataType: int64
		isHidden
		dataCategory: DayOfWeek
		summarizeBy: none
		isNameInferred
		isDataTypeInferred
		sourceColumn: DateAutoTemplate[Day of Week Number]

		annotation SQLBI_AttributeTypes = DayOfWeek

		annotation SQLBI_FilterSafe = True

	column 'Day of Week'
		dataType: string
		dataCategory: DayOfWeek
		summarizeBy: none
		isNameInferred
		isDataTypeInferred
		sourceColumn: DateAutoTemplate[Day of Week]
		sortByColumn: 'Day of Week Number'

		annotation SQLBI_FilterSafe = True

	column DateWithTransactions
		dataType: boolean
		isHidden
		summarizeBy: none
		isNameInferred
		isDataTypeInferred
		sourceColumn: DateAutoTemplate[DateWithTransactions]

		annotation SQLBI_AttributeTypes = DateDuration

	hierarchy Calendar

		level Year
			column: Year

		level Month
			column: 'Year Month'

		level Date
			column: Date

	partition Date = calculated
		mode: import
		source = DateAutoTemplate

	annotation SQLBI_Template = Dates

	annotation SQLBI_TemplateTable = Date

	annotation SQLBI_CalendarType = Calendar

