table Spotify_Dataset
	lineageTag: 36235c27-d341-4b48-b100-48bf4003972b

	measure 'Max Streams' = MAX(Spotify_Dataset[streams])
		formatString: 0
		lineageTag: 819b501c-acca-4587-aaf2-27bee11ec8b5

	measure 'Top Song Streams' =
			
			CALCULATE(
			    SUM(Spotify_Dataset[streams]),
			    Spotify_Dataset[streams] = MAX(Spotify_Dataset[streams])
			)
		formatString: 0
		lineageTag: 17d5aac1-d8e9-46ac-bb11-ff2996cbf09c

	measure 'Average Stream per Year' =
			
			CALCULATE(
			    AVERAGE(Spotify_Dataset[streams]),
			    ALLEXCEPT(Spotify_Dataset, Spotify_Dataset[Date])
			)
		lineageTag: 96eadeea-bfc3-458b-a394-b3ebd423d84f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Top Song vs Avg Value' =
			
			DIVIDE(
			    [Top Song Streams] - [Average Stream per Year],
			    [Average Stream per Year]
			)
		lineageTag: 2053d6d9-5d6d-4ddd-ad3e-3f864f461e6a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Top song vs AVG' =
			
			VAR X = [Top Song vs Avg Value]
			RETURN
			IF(
			    X > 0,
			    FORMAT(X, "#0.0%") & " " & UNICHAR(9650),
			    FORMAT(X, "#0.0%") & " " & UNICHAR(9660)
			)
		lineageTag: 5fc52720-2b14-4f62-9f32-9df766858dc2

	measure 'Image HTML' = ```
			
			Var x = 
			CALCULATE(
			    MAX(Spotify_Dataset[cover_url]),
			    Spotify_Dataset[streams] = MAX(Spotify_Dataset[streams])
			)
			
			RETURN
			
			"
			<!DOCTYPE html>
			<html lang='en'>
			<head>
			    <meta charset='UTF-8'>
			    <title>Image Cropping</title>
			    <style>
			        .image-container {
			            width: 318px; /* Width of the container */
			            height: 100px; /* Height of the container */
			            overflow: hidden; /* Hide parts of the image that don't fit */
			            border-radius: 12px; /* Rounded corners */
			            position: relative; /* Relative positioning for the child element */
			        }
			        .image {
			            object-fit: cover; /* Cover the entire container */
			            object-position: center; /* Center the image */
			            width: 100%; /* Full width */
			            height: 100%; /* Full height */
			        }
			    </style>
			</head>
			<body>
			    <div class='image-container'>
			        <img src='"&x&"' alt='Album Cover' class='image'>
			    </div>
			</body>
			</html>
			"
			
			```
		lineageTag: 8ba5e757-4ede-43b3-ba2a-8b01af987ff9

	measure Percent_Val =
			
			AVERAGE([energy_%])
		lineageTag: ce0fadf7-d482-4ffb-9333-d8cf26ae715c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure _Track = COUNT(Spotify_Dataset[track_name])
		formatString: 0
		lineageTag: 3ef3516a-c55a-41e5-a762-31f96aafee84

	column track_name
		dataType: string
		lineageTag: b1267688-ef87-4607-822b-9dc5de2281b2
		summarizeBy: none
		sourceColumn: track_name

		annotation SummarizationSetBy = Automatic

	column artist(s)_name
		dataType: string
		lineageTag: 42e8f002-f688-41b2-8571-cf1223e3606f
		summarizeBy: none
		sourceColumn: artist(s)_name

		annotation SummarizationSetBy = Automatic

	column artist_count
		dataType: int64
		formatString: 0
		lineageTag: f8e1812a-f7b5-4169-ba2a-84f18f8de283
		summarizeBy: sum
		sourceColumn: artist_count

		annotation SummarizationSetBy = Automatic

	column released_year
		dataType: int64
		formatString: 0
		lineageTag: cced3eb4-eec0-4b0a-8422-e079bd01ec63
		summarizeBy: sum
		sourceColumn: released_year

		annotation SummarizationSetBy = Automatic

	column released_month
		dataType: int64
		formatString: 0
		lineageTag: fc42519d-aa20-49cc-95c1-5e35bade8fa1
		summarizeBy: sum
		sourceColumn: released_month

		annotation SummarizationSetBy = Automatic

	column released_day
		dataType: int64
		formatString: 0
		lineageTag: 093a5a1f-c1cc-45d8-80eb-060c559f0a1f
		summarizeBy: sum
		sourceColumn: released_day

		annotation SummarizationSetBy = Automatic

	column in_spotify_playlists
		dataType: int64
		formatString: 0
		lineageTag: 135f2b92-e5ba-48de-825f-c912e67f79c4
		summarizeBy: sum
		sourceColumn: in_spotify_playlists

		annotation SummarizationSetBy = Automatic

	column in_spotify_charts
		dataType: int64
		formatString: 0
		lineageTag: 893f7a06-80bb-42c8-acbe-ce6c1d7d5a3a
		summarizeBy: sum
		sourceColumn: in_spotify_charts

		annotation SummarizationSetBy = Automatic

	column streams
		dataType: int64
		formatString: 0
		lineageTag: 92ea67bc-b0ba-4bc1-884c-bcad03346bec
		summarizeBy: sum
		sourceColumn: streams

		annotation SummarizationSetBy = Automatic

	column in_apple_playlists
		dataType: int64
		formatString: 0
		lineageTag: 0ae2ba3e-7ba1-4bdc-a5d3-7589823f5014
		summarizeBy: sum
		sourceColumn: in_apple_playlists

		annotation SummarizationSetBy = Automatic

	column in_apple_charts
		dataType: int64
		formatString: 0
		lineageTag: 687e22c3-13f4-404d-bbce-5dff2c1324ed
		summarizeBy: sum
		sourceColumn: in_apple_charts

		annotation SummarizationSetBy = Automatic

	column in_deezer_playlists
		dataType: int64
		formatString: 0
		lineageTag: 1847a4e8-474b-46a2-a380-f5627167d555
		summarizeBy: sum
		sourceColumn: in_deezer_playlists

		annotation SummarizationSetBy = Automatic

	column in_deezer_charts
		dataType: int64
		formatString: 0
		lineageTag: 92d49a01-6a8c-48cc-8598-034087ee21b9
		summarizeBy: sum
		sourceColumn: in_deezer_charts

		annotation SummarizationSetBy = Automatic

	column in_shazam_charts
		dataType: int64
		formatString: 0
		lineageTag: 043d6680-3753-40a4-a683-1763e1bf561d
		summarizeBy: sum
		sourceColumn: in_shazam_charts

		annotation SummarizationSetBy = Automatic

	column bpm
		dataType: int64
		formatString: 0
		lineageTag: 39b26976-b1c9-461b-9c40-cae7effa23a5
		summarizeBy: sum
		sourceColumn: bpm

		annotation SummarizationSetBy = Automatic

	column key
		dataType: string
		lineageTag: 3b585311-909f-4b4d-bd2a-a780b51461e4
		summarizeBy: none
		sourceColumn: key

		annotation SummarizationSetBy = Automatic

	column mode
		dataType: string
		lineageTag: c4fb4de9-1f41-45d9-b6b3-6658af552fa4
		summarizeBy: none
		sourceColumn: mode

		annotation SummarizationSetBy = Automatic

	column danceability_%
		dataType: int64
		formatString: 0
		lineageTag: 879d44cd-921d-48c2-9c6d-b4963364d319
		summarizeBy: sum
		sourceColumn: danceability_%

		annotation SummarizationSetBy = Automatic

	column valence_%
		dataType: int64
		formatString: 0
		lineageTag: b8ffe94a-7999-4b5b-b46e-4149699fd62b
		summarizeBy: sum
		sourceColumn: valence_%

		annotation SummarizationSetBy = Automatic

	column energy_%
		dataType: int64
		formatString: 0
		lineageTag: 0b0dc0fa-ec67-4c98-ba15-6b003260f4f1
		summarizeBy: sum
		sourceColumn: energy_%

		annotation SummarizationSetBy = Automatic

	column acousticness_%
		dataType: int64
		formatString: 0
		lineageTag: a149770b-1c17-4a9e-81e0-2fd9c535c750
		summarizeBy: sum
		sourceColumn: acousticness_%

		annotation SummarizationSetBy = Automatic

	column instrumentalness_%
		dataType: int64
		formatString: 0
		lineageTag: 1480bdd6-ce44-4941-b347-7ead42d6bf2e
		summarizeBy: sum
		sourceColumn: instrumentalness_%

		annotation SummarizationSetBy = Automatic

	column liveness_%
		dataType: int64
		formatString: 0
		lineageTag: 10e3b17e-d9d5-4e9b-b3c2-ad7dc72ba256
		summarizeBy: sum
		sourceColumn: liveness_%

		annotation SummarizationSetBy = Automatic

	column speechiness_%
		dataType: int64
		formatString: 0
		lineageTag: e5aa6eef-82d2-495c-ae87-114f2aa4e5b5
		summarizeBy: sum
		sourceColumn: speechiness_%

		annotation SummarizationSetBy = Automatic

	column cover_url
		dataType: string
		lineageTag: 91b09753-4d7e-4242-b378-fd69903860e2
		summarizeBy: none
		sourceColumn: cover_url

		annotation SummarizationSetBy = Automatic

	column Date = DATE([released_year], [released_month], [released_day])
		dataType: dateTime
		formatString: Short Date
		lineageTag: 838caf8e-d727-4b31-94dc-778f78a2b568
		summarizeBy: none
		isDataTypeInferred

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition Spotify_Dataset = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents(Bihaag_DIR), null, true),
				    #"Spotify Dataset_Sheet" = Source{[Item="Spotify Dataset",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Spotify Dataset_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"track_name", type any}, {"artist(s)_name", type text}, {"artist_count", Int64.Type}, {"released_year", Int64.Type}, {"released_month", Int64.Type}, {"released_day", Int64.Type}, {"in_spotify_playlists", Int64.Type}, {"in_spotify_charts", Int64.Type}, {"streams", Int64.Type}, {"in_apple_playlists", Int64.Type}, {"in_apple_charts", Int64.Type}, {"in_deezer_playlists", Int64.Type}, {"in_deezer_charts", Int64.Type}, {"in_shazam_charts", Int64.Type}, {"bpm", Int64.Type}, {"key", type text}, {"mode", type text}, {"danceability_%", Int64.Type}, {"valence_%", Int64.Type}, {"energy_%", Int64.Type}, {"acousticness_%", Int64.Type}, {"instrumentalness_%", Int64.Type}, {"liveness_%", Int64.Type}, {"speechiness_%", Int64.Type}, {"cover_url", type text}}),
				    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Changed Type", {"streams"})
				in
				    #"Removed Errors"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

