table Date
	lineageTag: 6abb3a26-3e9b-410f-87d7-fc5d26ff0519
	dataCategory: Time

	measure _ShowValueForDates =
			
			VAR __LastDateWithData =
			    CALCULATE (
			        MAXX ( { MAX ( 'Spotify_Dataset'[Date] ) }, ''[Value] ),
			        REMOVEFILTERS ()
			    )
			VAR __FirstDateVisible =
			    MIN ( 'Date'[Date] )
			VAR __Result =
			    __FirstDateVisible <= __LastDateWithData
			RETURN
			    __Result
		isHidden
		displayFolder: Hidden Time Intelligence
		lineageTag: 94d7b60f-367a-4c3a-8c60-4017f6667ccf

		annotation SQLBI_Template = TimeIntelligence

		annotation SQLBI_TimeIntelligence = Standard

		annotation SQLBI_CalendarType = Calendar

	column Date
		dataType: dateTime
		isKey
		formatString: m/d/yyyy
		lineageTag: 42b8bb83-767c-4b9f-885b-0fe4229380c5
		dataCategory: PaddedDateTableDates
		summarizeBy: none
		isNameInferred
		isDataTypeInferred
		sourceColumn: DateAutoTemplate[Date]

		annotation SQLBI_AttributeTypes = Date

	column Year
		dataType: int64
		lineageTag: 6f531b1b-fce2-4730-a4bd-f14c1c1448a7
		dataCategory: Years
		summarizeBy: none
		isNameInferred
		isDataTypeInferred
		sourceColumn: DateAutoTemplate[Year]

	column 'Year Quarter Number'
		dataType: int64
		isHidden
		lineageTag: dd3d40ef-a151-493f-9fb7-9bd9ec8e58c4
		dataCategory: Quarters
		summarizeBy: none
		isNameInferred
		isDataTypeInferred
		sourceColumn: DateAutoTemplate[Year Quarter Number]

	column 'Year Quarter'
		dataType: string
		lineageTag: f83dba4a-7df2-4ead-aa03-52761453ec92
		dataCategory: Quarters
		summarizeBy: none
		isNameInferred
		isDataTypeInferred
		sourceColumn: DateAutoTemplate[Year Quarter]
		sortByColumn: 'Year Quarter Number'

	column Quarter
		dataType: string
		lineageTag: 2cc5c1e8-b7fb-4e7c-a938-84a3e299dc47
		dataCategory: QuarterOfYear
		summarizeBy: none
		isNameInferred
		isDataTypeInferred
		sourceColumn: DateAutoTemplate[Quarter]

	column 'Year Month'
		dataType: string
		lineageTag: 288fabfc-1249-439a-b773-bdceb8697cf5
		dataCategory: Months
		summarizeBy: none
		isNameInferred
		isDataTypeInferred
		sourceColumn: DateAutoTemplate[Year Month]
		sortByColumn: 'Year Month Number'

	column 'Year Month Number'
		dataType: int64
		isHidden
		lineageTag: b46965cc-35b0-48fc-b4f5-138e515d14ec
		dataCategory: Months
		summarizeBy: none
		isNameInferred
		isDataTypeInferred
		sourceColumn: DateAutoTemplate[Year Month Number]

	column Month
		dataType: string
		lineageTag: ab841db2-418b-419d-956d-416a72664d88
		dataCategory: MonthOfYear
		summarizeBy: none
		isNameInferred
		isDataTypeInferred
		sourceColumn: DateAutoTemplate[Month]
		sortByColumn: 'Month Number'

	column 'Month Number'
		dataType: int64
		isHidden
		lineageTag: 6657738a-2728-4771-9c5b-0e3d9c810d43
		dataCategory: MonthOfYear
		summarizeBy: none
		isNameInferred
		isDataTypeInferred
		sourceColumn: DateAutoTemplate[Month Number]

	column 'Day of Week Number'
		dataType: int64
		isHidden
		lineageTag: 18a20896-c2a5-4ae3-be78-8ff2ae124980
		dataCategory: DayOfWeek
		summarizeBy: none
		isNameInferred
		isDataTypeInferred
		sourceColumn: DateAutoTemplate[Day of Week Number]

		annotation SQLBI_AttributeTypes = DayOfWeek

		annotation SQLBI_FilterSafe = True

	column 'Day of Week'
		dataType: string
		lineageTag: c1254ed1-265b-4d6d-b555-476cc94d079b
		dataCategory: DayOfWeek
		summarizeBy: none
		isNameInferred
		isDataTypeInferred
		sourceColumn: DateAutoTemplate[Day of Week]
		sortByColumn: 'Day of Week Number'

		annotation SQLBI_FilterSafe = True

	column DateWithTransactions
		dataType: boolean
		isHidden
		lineageTag: 1034fd0b-4a5b-4692-8e5c-93d8609d7b4d
		summarizeBy: none
		isNameInferred
		isDataTypeInferred
		sourceColumn: DateAutoTemplate[DateWithTransactions]

		annotation SQLBI_AttributeTypes = DateDuration

	hierarchy Calendar
		lineageTag: b4165352-151a-4c75-a5af-c2c4563d392f

		level Year
			lineageTag: 760329e8-6d09-4629-993d-b2894600640f
			column: Year

		level Month
			lineageTag: b89571ae-06a2-46f9-bb9b-26c427070d3b
			column: 'Year Month'

		level Date
			lineageTag: 9eb5aaf2-327c-4d10-b820-2034073a79d5
			column: Date

	partition Date = calculated
		mode: import
		source = DateAutoTemplate

	annotation SQLBI_Template = Dates

	annotation SQLBI_TemplateTable = Date

	annotation SQLBI_CalendarType = Calendar

