table DIM_DATE
	lineageTag: ae33c702-6ed4-4a7f-85fd-24c3ad6b874a

	column YearMonth
		dataType: string
		lineageTag: 69822606-57eb-48cf-82aa-cba13ab139fd
		summarizeBy: none
		sourceColumn: YearMonth

		annotation SummarizationSetBy = Automatic

	column 'Reporting Period'
		dataType: dateTime
		formatString: mmmm yyyy
		lineageTag: bb9f4ace-e886-4cae-8954-6c5dfb7a454d
		summarizeBy: none
		sourceColumn: Reporting Period

		variation Variation
			isDefault
			relationship: 8a19699c-471f-4102-b53d-ab0f46cb3e16
			defaultHierarchy: LocalDateTable_f87fa9e8-7d25-425d-b169-ecb331113ac9.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Month Name'
		dataType: string
		lineageTag: b3d92b9d-8968-4cc1-be2c-4ea4f808ff00
		summarizeBy: none
		sourceColumn: Month Name

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: b1982322-ba7e-4e46-a3e3-ca6fb541ae97
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Month Number'
		dataType: string
		lineageTag: 41c35b83-6310-4b50-8c02-e40f24c0a21d
		summarizeBy: none
		sourceColumn: Month Number

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: int64
		formatString: 0
		lineageTag: 79537f64-2fa6-475a-bddd-e30db069e498
		summarizeBy: sum
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column 'Year Rank' = RANKX(DIM_DATE,DIM_DATE[Year],,DESC,Dense)
		dataType: string
		lineageTag: 3d4e8a67-9100-4ce2-b824-b2066e2c9533
		summarizeBy: none

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'Month (Short)' = FORMAT(DIM_DATE[Reporting Period],"mmm")&"."
		dataType: string
		lineageTag: a6425fcf-edc3-4f5b-86ab-fdf58ecf7ac6
		summarizeBy: none
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	partition DIM_DATE-e8d08b2c-8670-4325-a366-5edb999ad130 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents(Sharepoint_Dataset_URL), null, true),
				    FACT_SALES_Table = Source{[Item="FACT_SALES",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(FACT_SALES_Table,{{"Segment", type text}, {"Country", type text}, {"Product", type text}, {"Discount Band", type text}, {"Units Sold", type number}, {"Manufacturing Price", Int64.Type}, {"Sale Price", Int64.Type}, {"Gross Sales", type number}, {"Discounts", type number}, {" Sales", type number}, {"COGS", type number}, {"Profit", type number}, {"Date", type date}, {"Month Number", Int64.Type}, {"Month Name", type text}, {"Year", Int64.Type}, {"Manager ID", type text}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type", "Custom", each Number.ToText([Month Number],"00")),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom",{{"Custom", type text}}),
				    #"Added Custom1" = Table.AddColumn(#"Changed Type1", "YearMonth", each Number.ToText([Year],"0000")&[Custom]),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom1",{{"YearMonth", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type2",{"Segment", "Country", "Product", "Discount Band", "Units Sold", "Manufacturing Price", "Sale Price", "Gross Sales", "Discounts", " Sales", "COGS", "Profit", "Manager ID", "Month Number"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"Custom", "Month Number"}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns",{"YearMonth", "Date", "Month Name", "Year", "Month Number"}),
				    #"Sorted Rows" = Table.Sort(#"Reordered Columns",{{"YearMonth", Order.Ascending}}),
				    #"Added Index" = Table.AddIndexColumn(#"Sorted Rows", "Index", 0, 1, Int64.Type),
				    #"Removed Duplicates" = Table.Distinct(#"Added Index", {"YearMonth"}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Removed Duplicates",{"Index"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns1",{{"Date", "Reporting Period"}}),
				    #"Inserted Quarter" = Table.AddColumn(#"Renamed Columns1", "Quarter", each Date.QuarterOfYear([Reporting Period]), Int64.Type)
				in
				    #"Inserted Quarter"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

