table FACT_SALES
	lineageTag: 926f519f-4655-46d4-b6d9-34b7b67312f5

	column YearMonth
		dataType: string
		lineageTag: 6e429de5-3791-411e-be70-5c51f2a21f86
		summarizeBy: none
		sourceColumn: YearMonth

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 8a991fe8-703e-4785-897a-1b07423bd201
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 9cd752c8-b3a1-404d-ade6-bcce3da57078
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Product
		dataType: string
		lineageTag: 9435ac6a-e1f6-45aa-93be-a5530fb4720e
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column 'Discount Band'
		dataType: string
		lineageTag: 7902d7d7-d518-4379-b05b-de96eeabce4f
		summarizeBy: none
		sourceColumn: Discount Band

		annotation SummarizationSetBy = Automatic

	column 'Manager ID'
		dataType: string
		lineageTag: 6a100a62-76e1-4b15-aee7-02cc9f3d59a6
		summarizeBy: none
		sourceColumn: Manager ID

		annotation SummarizationSetBy = Automatic

	column 'Units Sold'
		dataType: int64
		formatString: 0
		lineageTag: c7f31d1b-27c3-471e-b362-5ba62c9d4950
		summarizeBy: sum
		sourceColumn: Units Sold

		annotation SummarizationSetBy = Automatic

	column 'Manufacturing Price'
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 21e6f92b-41a1-405e-8f1b-40ada1eaa26b
		summarizeBy: sum
		sourceColumn: Manufacturing Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Sales Price'
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 83102948-9afa-461d-969f-3388d79306d6
		summarizeBy: sum
		sourceColumn: Sales Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Gross Sales'
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 66b5a7c5-48e5-4b93-bbbe-9ddf8ee162f7
		summarizeBy: sum
		sourceColumn: Gross Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Discounts
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 4ce416d9-4d22-451e-b816-540b36e700b9
		summarizeBy: sum
		sourceColumn: Discounts

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Sales
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 7f943547-51f8-40e6-bb40-f86986319462
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column COGs
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 31a9ce8b-440e-41e2-9a50-5e1d4308f3a2
		summarizeBy: sum
		sourceColumn: COGs

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Profit
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 63ea26b6-2d7c-4cc9-beb6-984c2f9e1ff0
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Discount Band ID'
		dataType: int64
		formatString: 0
		lineageTag: 50d46186-1f52-4695-bb09-904a65bdaa5b
		summarizeBy: count
		sourceColumn: Discount Band ID

		annotation SummarizationSetBy = Automatic

	column 'Product Name (Short)'
		dataType: string
		lineageTag: 86d83c44-2b7c-47b6-8abd-993717767f82
		summarizeBy: none
		sourceColumn: Product Name (Short)

		annotation SummarizationSetBy = Automatic

	column 'Segment Short Name' =
			
			SWITCH(
			    [Segment],
			    "Government", "Gov",
			    "Channel Partners", "CP",
			    "Enterprise", "Ent",
			    "Midmarket", "MM",
			    "Small Business", "Small Biz"
			)
		dataType: string
		lineageTag: 70d73b99-5e13-4f12-b4a8-43722de55a71
		summarizeBy: none
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column 'Country Short Name' =
			
			SWITCH(
			    [Country],
			    "United States", "USA",
			    FACT_SALES[Country]
			)
		dataType: string
		lineageTag: 66a4dc50-d39c-4365-bcba-edb2bf6bc3fa
		summarizeBy: none
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	partition FACT_SALES-3db8af81-fc4a-4c68-af78-84fccec0187c = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents(Sharepoint_Dataset_URL), null, true),
				    FACT_SALES_Table = Source{[Item="FACT_SALES",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(FACT_SALES_Table,{{"Segment", type text}, {"Country", type text}, {"Product", type text}, {"Discount Band", type text}, {"Units Sold", type number}, {"Manufacturing Price", Int64.Type}, {"Sale Price", Int64.Type}, {"Gross Sales", type number}, {"Discounts", type number}, {" Sales", type number}, {"COGS", type number}, {"Profit", type number}, {"Date", type date}, {"Month Number", Int64.Type}, {"Month Name", type text}, {"Year", Int64.Type}, {"Manager ID", type text}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type", "Custom", each Number.ToText([Month Number],"00")),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom",{{"Custom", type text}}),
				    #"Added Custom1" = Table.AddColumn(#"Changed Type1", "YearMonth", each Number.ToText([Year],"0000")&[Custom]),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom1",{{"YearMonth", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type2",{"Custom", "Date", "Month Number", "Month Name", "Year"}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Removed Columns",{"YearMonth", "Segment", "Country", "Product", "Discount Band", "Units Sold", "Manufacturing Price", "Sale Price", "Gross Sales", "Discounts", " Sales", "COGS", "Profit", "Manager ID"}),
				    #"Grouped Rows" = Table.Group(#"Reordered Columns", {"YearMonth", "Segment", "Country", "Product", "Discount Band", "Manager ID"}, {{"Units Sold", each List.Sum([Units Sold]), type nullable number}, {"Manufacturing Price", each List.Average([Manufacturing Price]), type nullable number}, {"Sales Price", each List.Average([Sale Price]), type nullable number}, {"Gross Sales", each List.Sum([Gross Sales]), type nullable number}, {"Discounts", each List.Sum([Discounts]), type nullable number}, {"Sales", each List.Sum([#" Sales"]), type nullable number}, {"COGs", each List.Sum([COGS]), type nullable number}, {"Profit", each List.Sum([Profit]), type nullable number}}),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Grouped Rows",{{"Units Sold", Int64.Type}, {"Manufacturing Price", Currency.Type}, {"Sales Price", Currency.Type}, {"Gross Sales", Currency.Type}, {"Discounts", Currency.Type}, {"Sales", Currency.Type}, {"COGs", Currency.Type}, {"Profit", Currency.Type}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type3","United States of America","United States",Replacer.ReplaceText,{"Country"}),
				    #"Added Conditional Column" = Table.AddColumn(#"Replaced Value", "Discount Band ID", each if Text.Contains([Discount Band], "High") then 1 else if Text.Contains([Discount Band], "Medium") then 2 else if Text.Contains([Discount Band], "Low") then 3 else if Text.Contains([Discount Band], "None") then 4 else 0),
				    #"Changed Type4" = Table.TransformColumnTypes(#"Added Conditional Column",{{"Discount Band ID", Int64.Type}}),
				    #"Inserted First Characters" = Table.AddColumn(#"Changed Type4", "First Characters", each Text.Start([Product], 5), type text),
				    #"Renamed Columns" = Table.RenameColumns(#"Inserted First Characters",{{"First Characters", "Product Name (Short)"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

